kind: Service
apiVersion: v1
metadata:
  name: pheonix-go-service
spec:
  type: NodePort
  selector:
    app: pheonix-nginx
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80