apiVersion: apps/v1
kind: Deployment
metadata:
  name: pheonix-nginx
  labels:
    app: pheonix-nginx
spec:
  selector:
    matchLabels:
      app: pheonix-nginx
      tier: web
  template:
    metadata:
      labels:
        app: pheonix-nginx
        tier: web
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
          - name: aws-config-volume
            mountPath: /etc/config
        - name: pacific-links-v1
          image: pacific-links-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: aws-config-volume
              mountPath: /etc/config

      volumes:
      - name: aws-config-volume
        configMap:
          name: aws-config
      restartPolicy: Always