apiVersion: apps/v1
kind: Deployment
metadata:
  name: pheonix-nginx-deployment
  labels:
    app: pheonix-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pheonix-nginx
      tier: web
  template:
    metadata:
      labels:
        app: pheonix-nginx
        tier: web
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.0
          ports:
            - containerPort: 80
         # volumeMounts:
          #- name: aws-config-volume
           # mountPath: /etc/config
#        - name: pacific-links-v1
#          image: pacific-links-v1
#          imagePullPolicy: Never
#          ports:
#            - containerPort: 8080
#          volumeMounts:
#            - name: aws-config-volume
#              mountPath: /etc/config
#
#      volumes:
#      - name: aws-config-volume
#        configMap:
#          name: aws-config
#      restartPolicy: Always