kind: Service
apiVersion: v1
metadata:
  name: pheonix-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: pheonix-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80